### ISSUE TITLE
Helm chart update for 0.1.2 app version

### ISSUE THREAD

**Issue by ibalat** [mshade/kronic#43]
Hi, latest Helm chart (0.1.4) support v0.1.1 app version at https://artifacthub.io/packages/helm/kronic/kronic address. Will you update it for 0.1.2 app version?

**Comment by mshade** [comment]
I'll make a round of updates! Didn't realize anyone was actually using this yet :)

**Comment by ibalat** [comment]
We are using it with lovely :) Thanks again for your effort and contributes <3

**Comment by mshade** [comment]
@ibalat I've released app version 0.1.3 and chart version 0.1.6! If you are still on v0.1.1, note that v0.1.2 introduced basic auth on the backend, enabled by default. If you are handling auth your own way, you can set that to disabled. Otherwise, I'd recommend creating a secret with the admin password and setting the helm value `auth.existingSecretName` to the name of that secret. Instructions are in the READMEs :)

Let me know of any issues or feature requests you have. I have limited time these days, but I'm happy to see this is useful for someone.

**Comment by ibalat** [comment]
thank you friend, I will check it all of them and update it 🎉
